jobs:
  fmt:
    command: black . --exclude venv
    targets:
      - all

  yenv:
    function: yenv:main
    context:
      yenv-file: environment.yml
      env-targets:
        - templ8

  main-env:
    command: export ${cat templ8.env}
  
  template:
    command: templ8 ./template.yml .

  docs:
    command: python setup.py updateDocs
  
  clean:
    function: clean:main
    context:
      clean_dirs:
        - build
        - dist
        - templ8.egg-info

  pypi-upload:
    function: pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz

  purge:
    command: purge templ8 joellefkowitz

projects:
  templ8:
    path: ../templ8

routines:
  pre-release:
    - fmt
    - clean
    - docs


