jobs:
  yenv:
    command: yenv print <yenv_file> <env-target> dotenv -f -s
    context:
      yenv-file: environment.yml
      env-targets:
        - {{src}}

  export-env:
    command: export ${cat {{name}}.env}
  
  template:
    command: templ8 ./template.yml .

projects:
  {{src}}:
    path: {{src}}

meta:
  script_root: ../../scripts/
  project_root: ../../../
