version: '3.3'

  services:
    {{webapp}}:
      image: {{webapp}}:{{version}}
      ports: 
        - 443:443

{% if server %}
    {{server}}:
      image: {{server}}:{{version}}
      depends_on: 
        - database
        - cache

    database:
      image: postgres:latest

    cache:
      image: memchaced:latest
{% endif %}
